### PR TITLE
Add Go 1.8, 1.9 to Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by dlebech** [comment]
Thanks @gliptak. Could you change the target branch to the `v1` branch. As mentioned in the README, `master` is not being maintained anymore. (I have been unable to change the default branch to `v1` so far, because I don't have proper access.)

**Comment by gliptak** [comment]
The ```branches```/```only``` might work for this
https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
I will also add https://docs.travis-ci.com/user/languages/go/#Go-Import-Path

**Comment by dlebech** [comment]
@gliptak Sorry for not being clear. I meant the target branch on Github to merge your changes to should be `jarcoal:v1` instead of `jarcoal:master`. Does that make sense?

Travis builds work fine with the `v1` branch. What I meant by "not being able to change to default branch" is that when you visit the repo on github, it should show the v1 branch by default, but I don't have access to change that setting.

**Comment by gliptak** [comment]
@dlebech Got you. Sorry that I misread your comment. I will resubmit to ```v1```.

**Pull request closed without merging**
