### PR TITLE
Travis-ci: added support for ppc64le

### PR DESCRIPTION
**Pull request by dthadi3**
Signed-off-by: Devendranath Thadi <devendranath.thadi3@gmail.com>

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing.

### CODE REVIEW

**Comment by maxatome** [comment]
Hello,
Thanks for working on a PR! 
We will leave travis before the end of the year as they changed their pricing model recently.
So in the coming weeks it will be replaced by Github actions, work is in progress.

Why do you need to build httpmock on a specific arch? As it does not use special OS feature and do not rely on C code, it seems unnecessary to build it on different architectures.

**Comment by dthadi3** [comment]
@maxatome Thanks for your response, @gerrith3 can you please respond to his query.

**Comment by gerrith3** [comment]
@maxatome Travis's changes are a bit overblown - basically you start with a fixed number of credits but can easily request more free credits if you need.  The policy is pretty much the same as GH Actions or CircleCI, so the change shouldn't have to be the driver to move to GHA.  Obviously, if you prefer that, that's fine, but at the moment they don't have support for testing other architectures.  You can request additional free credits here:  https://support.travis-ci.com/hc/en-us/signin - they just request your travis/github ID and which or how many repositories.  They are primarily trying to cut down on bitcoin miners and other illegitamate uses.

As far as being arch independent, you may know that but outsiders porting to distros and such can't verify that.  Testing is a way of confirming and documenting that support.  This package is already included in debian/ubuntu ppc64le distros and possibly others, so this should be an easy win to document and continue testing - ensuring no regressions in support for other archs.

**Comment by maxatome** [comment]
@gerrith3 as previously said, httpmock does not use OS specific tricks. If I follow your requirements to the letter, I have to deploy tests for all OSes and architectures golang supports natively, why only linux+ppc64le/amd64? I agree to do this if we have some specific files for a specific OS or a specific architecture, but it is not the case here. httpmock is pure go.

My concern is to be sure it runs on last patch level version of each go release since 1.7. golang makes sure of the rest.

I think it is more appropriate each packager runs the tests before packaging a module. This way, he/she is sure the module compiles/runs on the specific platform he/she runs.

Luckily, httpmock does not use any external dependency and do not require a specific setup to run its tests excluding the availability of go itself, of course, so it is quite easy.

**Comment by gerrith3** [comment]
@maxatome A couple of comments - 1) Travis is changing their model but it barely affects open source project - basically everyone is on a credit system now, and as a maintainer you can request additional free credits at any time via support.travis-ci.com.  Their access policies for CI are pretty much identical still to GitHub Actions and CircleCI, but they also offer additional architectures that you can test, which GHA does not currently support (we are working on that but no ETA yet).

As far as packagers testing, we are talking about potentially some 80,000 projects that get packaged, often by people with no knowledge of the project.  We are trying to shift that burden and cost from being replicated for each distro, along with all the requisite hardware needed by each team to top of development tree, where fixing any regressions can happen immediately and be obvious as to the root cause.

As far as why ppc64le and not other architectures - our team is funded by IBM/Power and experts in that, including resources to test and validate changes to .travis.yml.  While I have no opposition to adding other architectures, it isn't our specialty, and we don't know which packages make the most sense to those architectures.  For instance we are currently going through the projects that are part of Ubuntu/Debian - it may be the same list for arm, but I don't know that.  However, if a third or fourth arcihtecture is interested, the work we are doing should be a pattern which would make it easier to add support.

With httpmock - like many projects, it is hard to tell if it is accidentally or even intentionally architecture independent just by looking at it.  We also don't know if our tests happen to pass because someone took ppc64le or other architecture into account previously when building.  All we can be sure of know is that it passes all of its testing now on ppc64le and thus submit the patch to help ensure its continued ability to run on ppc64le.

**Comment by dthadi3** [comment]
@maxatome waiting for your response. Thanks!

**Comment by maxatome** [comment]
Hello, as planned a few weeks ago, the repo just switched to Github Actions.
Be sure your users will receive a high level of support in case of problem, as I do for any opened issue.
Best regards.

**Pull request closed without merging**
